### ISSUE TITLE
Listing Dataset Landing Pages on redmine issue

### ISSUE THREAD

**Issue by adyork** [BCODMO/redmine_aws#3]
@ashepherd In the rest of the DM meeting we talked about readme stuff.  One thing we were wondering is if it is possible to show the list of Dataset # (or pages) associated with a redmine issue in the redmine issue itself.
Currently we can see the redmine # from an individual dataset landing page, but from the redmine issue we can't tell what datasets were made from that issue.
Our freetext notes templates has a notes section that we can manually fill in that dataset list but it would be better to just be able to display that if we already know it in the knowledge graph.  That way we wont get out of sync depending upon human freetext entry.  And it would save time to copy and paste all that and keep it up to date.
Thoughts?

ashepherd:house_with_garden:  12:31 PM
let me get back to you tomorrow. in a hack-a-thon the rest of the day
:+1:

ashepherd:house_with_garden:  5:38 PM
ah yeah, if we can modify the display (which I think we can with custom JS), we can make a call to the private SPARQL endpoint to list tthose datasets out. Let me write the query, and get that working, and then maybe @Conrad and I can work on that next Tuesday when we are in the office?

ashepherd:house_with_garden:  6:33 PM
here's an example query for redmine Issue` # 4078`
https://private.bco-dmo.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Furi+IF%[…]rmat=application%2Fsparql-results%2Bjson&timeout=0&debug=on

1 reply
Today at 7:39 AMView thread

ashepherd:house_with_garden:  7:46 AM
we can any other fields for a dataset or project as you want.
this JS in the browser worked
```
$('div#content div.attributes').first().append('<div id="bcodmo-osprey-query"></div>');

fetch("https://private.bco-dmo.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Furi+IF%28STRLEN%28%3Ftitle%29+%3E+0%2C+%3Ftitle%2C+%3Fshort_title%29+as+%3Flabel%0D%0AWHERE+%7B%0D%0A++%0D%0A++GRAPH+%3Chttps%3A%2F%2Fd2rq.bco-dmo.org%2Fid%2Fredmine%2F%3E+%7B+%0D%0A++++%3Furi+odo%3AtrackingIssue+%3Fissue+.%0D%0A++++%3Fissue+odo%3AidentifierValue+%224078%22%5E%5Exsd%3Atoken+.%0D%0A++++%3Fissue+odo%3AidentifierScheme+odo%3AIdentifierScheme_RedmineIssueTracker+.%0D%0A++%7D%0D%0A++%7B%0D%0A++++SERVICE+%3Chttps%3A%2F%2Flod.bco-dmo.org%2Fsparql%3E+%7B%0D%0A++++++%7B%0D%0A++++++++%3Furi+a+odo%3ADataset+.%0D%0A++++++++OPTIONAL+%7B%3Furi+odo%3AdatasetTitle+%3Ftitle+.%7D%0D%0A++++++++%3Furi+dcterms%3Atitle+%3Fshort_title+.%0D%0A++++++%7D+%0D%0A++++++UNION+%0D%0A++++++%7B%0D%0A++++++++%3Furi+a+odo%3AProject+.%0D%0A++++++++%3Furi+dcterms%3Atitle+%3Ftitle+.%0D%0A++++++++OPTIONAL+%7B%3Furi+odo%3AhasAcronym+%3Fshort_title+.%7D%0D%0A++++++%7D%0D%0A++++%7D%0D%0A++%7D%0D%0A%7D&should-sponge=&format=application%2Fsparql-results%2Bjson&timeout=0&debug=on").then(async (response) => {
  const data = await response.json();
  for (let key in data.results.bindings) {
    console.log(data.results.bindings[key].uri.value);
    console.log(data.results.bindings[key].label.value);
    let elem = document.getElementById('bcodmo-osprey-query');
    console.log(elem);
    elem.innerHTML = '<hr/><strong>OSPREY:</strong> <a href="' + data.results.bindings[key].uri.value + '" target="_blank">' + data.results.bindings[key].label.value + '</a>';
  }
})
```
![image](https://user-images.githubusercontent.com/9537357/131126824-a25f8ba4-8266-48e1-b8f1-27aaa1a0fcef.png)

adyork  8:10 AM
Oh wow!  I assume it isn't a problem that there are many OSPREY pages to a redmine issue?

ashepherd:house_with_garden:  8:11 AM
nope, it can list multiple. just need to figure out how to inject custom JS into the page

adyork  8:11 AM
That is amazing!

ashepherd:house_with_garden:  8:13 AM
well, also need to figure a solid way of grabbing the redmine issue from the DOM

adyork  8:15 AM
Now I'm thinking it might help another problem DMs have, that fact that we copy and paste so much.
Can it be like this so we can just copy and paste the whole list in our correspondence?  Would be a huge help.

> OSPREY:
> Dataset short name http://datasetpage.html
> Dataset short name 2 http://datasetpage2.html

Currently we are going back and forth multiple times to the osprey page to email copy short name, paste in email, copy url, paste in email so if a submission has 4 datasets we are going back and forth copy and pasting 8 times.

ashepherd:house_with_garden:  8:16 AM
yeah that shouldn't be an issue. let's figure out how challenging it is to inject custom JS into Redmine

**Comment by adyork** [comment]
@cschloer not sure if this is where this issue should go, I can move it if needed.

Not sure who should be the "assignee" here. 

@ashepherd as I mentioned this isn't highest priority, but it would make the DMs lives easier.  For now we are going to be hand curating these lists in the redmine issues in freetext as part of our Processing notes template.

**Comment by ashepherd** [comment]
Storing the SPARQL query:
```
SELECT DISTINCT ?uri IF(STRLEN(?title) > 0, ?title, ?short_title) as ?label

WHERE {
  
  GRAPH <https://d2rq.bco-dmo.org/id/redmine/> { 
    ?uri odo:trackingIssue ?issue .
    #?issue odo:identifierValue "4078"^^xsd:token .
    ?issue odo:identifierScheme odo:IdentifierScheme_RedmineIssueTracker .
  }
{
    SERVICE <https://lod.bco-dmo.org/sparql> {
      {
        ?uri a odo:Dataset .
        OPTIONAL {?uri odo:datasetTitle ?title .}
        ?uri dcterms:title ?short_title .
      } 
      UNION 
      {
        ?uri a odo:Project .
        ?uri dcterms:title ?title .
        OPTIONAL {?uri odo:hasAcronym ?short_title .}
      }
    }
  }
}
```

This is run against private.bco-dmo.org (only accessible to 128.128.x.x so we should expand that or use Digest auth or something).

**Comment by adyork** [comment]
From slack:

> 
> ![image](https://user-images.githubusercontent.com/9537357/131724942-042c7db2-5ad0-45f3-842c-ba74c2ed4694.png)
> 
> Conrad:house_with_garden: Today at 9:36 AM
> OK - redmine now has some osprey stuff! thanks to @ashepherd for the code.
> 
> 
> 
> 14 replies
> 
> Shannon Rauch  5 hours ago
> should it display multiple links if there's more than one dataset per ticket?
> 
> ashepherd:house_with_garden:  5 hours ago
> good question! shoudl this tickeet show more then 1 dataset?
> 
> Shannon Rauch  5 hours ago
> No, but here's one with 2 datasets and only one link in the OSPREY field: https://kato.bco-dmo.org/issues/4049
> 
> Conrad:house_with_garden:  4 hours ago
> I can update the code to pull them both in
> 
> ashepherd:house_with_garden:  4 hours ago
> Oh ok does the result set have them both already?!
> 
> Conrad:house_with_garden:  4 hours ago
> the result set has them both, the code was just overwriting the html to be whatever the last result was.
> :+1:
> 1
> 
> 
> ashepherd:house_with_garden:  4 hours ago
> oh my bad!!
> 
> Conrad:house_with_garden:  4 hours ago
> OK should be working now. Let me know if you want it to look at all different
![image](https://user-images.githubusercontent.com/9537357/131725147-292c3346-f742-4940-b731-d344f70d6e37.png)
> 
> 
> 
> adyork  4 hours ago
> So, in the github issue requesting this I asked if it is possible to provide these page links as a list with the short name and link so we can copy and paste that whole various places we need that.  Is that still posisble?
> ![image](https://user-images.githubusercontent.com/9537357/131725074-47832df0-3bfc-4e1c-a99a-1c0462639f0a.png)
> 
> 
> :+1:
> 1
> 
> 
> adyork  4 hours ago
> https://github.com/BCODMO/redmine_aws/issues/3
> 
> GitHubGitHub
> Listing Dataset Landing Pages on redmine issue · Issue #3 · BCODMO/redmine_aws
> @ashepherd In the rest of the DM meeting we talked about readme stuff. One thing we were wondering is if it is possible to show the list of Dataset # (or pages) associated with a redmine issue in t... (107 kB)
> https://github.com/BCODMO/redmine_aws/issues/3
> 
> 
> adyork  4 hours ago
> Or do people like having the full title?
> 
> adyork  4 hours ago
> But already so useful!
> :heavy_plus_sign:
> 1
> 
> 
> ashepherd:house_with_garden:  4 hours ago
> I can add the short name to the query
> 
> Shannon Rauch  3 hours ago
> @adyork I find the full titles hard to read. And they take up more space! Short names would be nice.
>

**Comment by adyork** [comment]
@cschloer / @ashepherd we talked about this in our meeting today and the final request for this is to list the 
Dataset Short Name and Dataset Landing Page link.
e.g. 
Landing Pages:

>   Polyp Bailout https://www.bco-dmo.org/dataset/855852 
>   Turf Polyp Counts https://www.bco-dmo.org/dataset/855867
>   Turf Tile Cover https://www.bco-dmo.org/dataset/855879

We identified the need for having the dataset ids easily available but since the dataset URLs have that as the last part of the link then that need is satisfied.  So the above format should work for everything.

**Comment by ashepherd** [comment]
SPARQL Query:
```
SELECT DISTINCT ?uri STR(?short_title) as ?short_title IF(STRLEN(?title) > 0, STR(?title), "") as ?title
WHERE {
  
  GRAPH <https://d2rq.bco-dmo.org/id/redmine/> { 
    ?uri odo:trackingIssue ?issue .
    ?issue odo:identifierValue "4078"^^xsd:token .
    ?issue odo:identifierScheme odo:IdentifierScheme_RedmineIssueTracker .
  }
{
    SERVICE <https://lod.bco-dmo.org/sparql> {
      {
        ?uri a odo:Dataset .
        OPTIONAL {?uri odo:datasetTitle ?title .}
        ?uri dcterms:title ?short_title .
      } 
      UNION 
      {
        ?uri a odo:Project .
        ?uri dcterms:title ?title .
        OPTIONAL {?uri odo:hasAcronym ?short_title .}
      }
    }
  }
}
```

https://private.bco-dmo.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Furi+STR%28%3Fshort_title%29+as+%3Fshort_title+IF%28STRLEN%28%3Ftitle%29+%3E+0%2C+STR%28%3Ftitle%29%2C+%22%22%29+as+%3Ftitle%0D%0AWHERE+%7B%0D%0A++%0D%0A++GRAPH+%3Chttps%3A%2F%2Fd2rq.bco-dmo.org%2Fid%2Fredmine%2F%3E+%7B+%0D%0A++++%3Furi+odo%3AtrackingIssue+%3Fissue+.%0D%0A++++%3Fissue+odo%3AidentifierValue+%224078%22%5E%5Exsd%3Atoken+.%0D%0A++++%3Fissue+odo%3AidentifierScheme+odo%3AIdentifierScheme_RedmineIssueTracker+.%0D%0A++%7D%0D%0A%7B%0D%0A++++SERVICE+%3Chttps%3A%2F%2Flod.bco-dmo.org%2Fsparql%3E+%7B%0D%0A++++++%7B%0D%0A++++++++%3Furi+a+odo%3ADataset+.%0D%0A++++++++OPTIONAL+%7B%3Furi+odo%3AdatasetTitle+%3Ftitle+.%7D%0D%0A++++++++%3Furi+dcterms%3Atitle+%3Fshort_title+.%0D%0A++++++%7D+%0D%0A++++++UNION+%0D%0A++++++%7B%0D%0A++++++++%3Furi+a+odo%3AProject+.%0D%0A++++++++%3Furi+dcterms%3Atitle+%3Ftitle+.%0D%0A++++++++OPTIONAL+%7B%3Furi+odo%3AhasAcronym+%3Fshort_title+.%7D%0D%0A++++++%7D%0D%0A++++%7D%0D%0A++%7D%0D%0A%7D&should-sponge=&format=application%2Fsparql-results%2Bjson&timeout=0&debug=on

**Comment by adyork** [comment]
This is great!
![image](https://user-images.githubusercontent.com/9537357/133141405-7d760c4d-03f4-4893-96be-0617e01ba114.png)

**Comment by adyork** [comment]
We touched on this in Slack, but can we get the Landing page URLs we would send to the public there instead of the "lod" URLs?

> 
> 
> adyork  14 days ago
> Question for @ashepherd, I can't remember when we should be using the "lod" links.  Like is that what we should be sending to submitters.  Any DMs know if it matters?
> http://lod.bco-dmo.org/id/dataset/772445
> vs
> https://www.bco-dmo.org/dataset/772445
> 
> ashepherd:house_with_garden:  [4:59 PM]
> Don’t send the LOD links. Those are just knowledge graph connections
> @Conrad would it be a hassle to update our OSPREY page list to use the non-lod links instead?
> 
> 
> ashepherd:house_with_garden:  14 days ago
> I’d need to rewrite the SPARQL query
>

**Comment by ashepherd** [comment]
```
SELECT DISTINCT ?uri ?url STR(?short_title) as ?short_title IF(STRLEN(?title) > 0, STR(?title), "") as ?title
WHERE {
  
  GRAPH <https://d2rq.bco-dmo.org/id/redmine/> { 
    ?uri odo:trackingIssue ?issue .
    ?issue odo:identifierValue "4078"^^xsd:token .
    ?issue odo:identifierScheme odo:IdentifierScheme_RedmineIssueTracker .
  }
{
    SERVICE <https://lod.bco-dmo.org/sparql> {
      {
        ?uri a odo:Dataset .
        OPTIONAL {?uri odo:datasetTitle ?title .}
        ?uri dcterms:title ?short_title .
        ?uri odo:osprey_page ?url .
      } 
      UNION 
      {
        ?uri a odo:Project .
        ?uri odo:osprey_page ?url .
        ?uri dcterms:title ?title .
        OPTIONAL {?uri odo:hasAcronym ?short_title .}
      }
    }
  }
}
```

Adds `url` binding to result set

https://private.bco-dmo.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Furi+%3Furl+STR%28%3Fshort_title%29+as+%3Fshort_title+IF%28STRLEN%28%3Ftitle%29+%3E+0%2C+STR%28%3Ftitle%29%2C+%22%22%29+as+%3Ftitle%0D%0AWHERE+%7B%0D%0A++%0D%0A++GRAPH+%3Chttps%3A%2F%2Fd2rq.bco-dmo.org%2Fid%2Fredmine%2F%3E+%7B+%0D%0A++++%3Furi+odo%3AtrackingIssue+%3Fissue+.%0D%0A++++%3Fissue+odo%3AidentifierValue+%224078%22%5E%5Exsd%3Atoken+.%0D%0A++++%3Fissue+odo%3AidentifierScheme+odo%3AIdentifierScheme_RedmineIssueTracker+.%0D%0A++%7D%0D%0A%7B%0D%0A++++SERVICE+%3Chttps%3A%2F%2Flod.bco-dmo.org%2Fsparql%3E+%7B%0D%0A++++++%7B%0D%0A++++++++%3Furi+a+odo%3ADataset+.%0D%0A++++++++OPTIONAL+%7B%3Furi+odo%3AdatasetTitle+%3Ftitle+.%7D%0D%0A++++++++%3Furi+dcterms%3Atitle+%3Fshort_title+.%0D%0A++++++++%3Furi+odo%3Aosprey_page+%3Furl+.%0D%0A++++++%7D+%0D%0A++++++UNION+%0D%0A++++++%7B%0D%0A++++++++%3Furi+a+odo%3AProject+.%0D%0A++++++++%3Furi+odo%3Aosprey_page+%3Furl+.%0D%0A++++++++%3Furi+dcterms%3Atitle+%3Ftitle+.%0D%0A++++++++OPTIONAL+%7B%3Furi+odo%3AhasAcronym+%3Fshort_title+.%7D%0D%0A++++++%7D%0D%0A++++%7D%0D%0A++%7D%0D%0A%7D&should-sponge=&format=application%2Fsparql-results%2Bjson&timeout=0

**Comment by cschloer** [comment]
![Screenshot from 2021-10-04 13-05-24](https://user-images.githubusercontent.com/7134143/135840828-433b7cf1-8a40-4e7d-9321-8f6251e6b2a2.png)
Should be working now. Let me know if anything else needs to be changed!

**Comment by adyork** [comment]
Perfect! What a time saver this is, having a list of datasets from the submission we can copy and paste in communications with the submitters.
