### ISSUE TITLE
Hide bottom "DELETE" button and make delete warning clearer

### ISSUE THREAD

**Issue by adyork** [BCODMO/redmine_aws#4]
We discussed this in our meeting today in order to prevent accidental issue deletes. This can happen when you think you are deleting the last comment in the issue and hit the bottom delete button.

In the meeting we said "Plan is to remove the delete button at the bottom of the Redmine issue ticket and leave the top one. The top “remove” message will be made more bold."

There are two delete buttons that delete the whole issue, one is at the top, one is at the bottom.

We are just requesting the bottom one be hidden (or removed).
![image](https://user-images.githubusercontent.com/9537357/131870736-e051862d-4893-478e-990d-bbf415cca334.png)

**Comment by adyork** [comment]
And the current message should be made more clear which currently reads:

![image](https://user-images.githubusercontent.com/9537357/131871109-b6316153-a117-435e-98d3-cc215a8b4f03.png)

We want it to say "Are you sure you want to delete the **entire** issue?"

**Comment by cschloer** [comment]
That text is the same whether you're deleting one or many issues. Are you
sure you want to change it to singular?

Amber York ***@***.***> schrieb am Do., 2. Sept. 2021, 11:22:

**Comment by adyork** [comment]
I think that is fine.

Also if you have other ideas for making the message bolder, I was maybe too literal. Danie clarified:

"Bold in that context = robust, strong, explicit... (not bold font)"

**Comment by adyork** [comment]
Sorry, I mean it is probably fine either way "issue" or "issue(s)"

In the context of how we practically delete if needed, it is from one page.  But I think that warning language is there because technically you can delete many if you select them from an overall issue search view.

**Comment by whshannon** [comment]
If we can make this say whatever we want, maybe even an additional warning like, 
"Are you sure you want to delete the **entire** issue(s)? Deleted issues can only be restored from AWS backups." 

(or whatever the correct terminology is there... just something to indicate that it's not super easy to get back once deleted.)

**Comment by cschloer** [comment]
I think it better to say "Deleted issues cannot be restored", even if that's not entirely correct. But it's certainly possible, if someone creates an issue in between backups and then deletes it, that it would be unrecoverable.

**Comment by cschloer** [comment]
And it perhaps makes it a little more drastic :)

**Comment by whshannon** [comment]
Yes, I like that!

**Comment by adyork** [comment]
So what I see is that all delete buttons (top and bottom) are hidden, not just the bottom one.  I've been out so checking on if that was what was eventually decided.  From other conversations and this issue I think the idea was we'd keep the top delete button with that warning.

**Comment by cschloer** [comment]
Should be fixed now.

**Comment by adyork** [comment]
looks great, thanks!
